In [129]:
import numpy as np


In [130]:
a_2d= np.array([[10,20,30],[23,55,15]])


In [131]:
another_type_array= np.array([[[1,2,3,4]]])

In [132]:
another_type_array

array([[[1, 2, 3, 4]]])

In [133]:
another_type_array.shape

(1, 1, 4)

In [134]:
another_type_array.ndim

3

In [135]:
a_2d

array([[10, 20, 30],
       [23, 55, 15]])

In [136]:
a_2d.dtype

dtype('int32')

In [137]:
a_2d.shape

(2, 3)

In [138]:
a_2d.ndim

2

In [139]:
a_2d.size

6

In [140]:
a_2d[0]

array([10, 20, 30])

In [141]:
a_2d

array([[10, 20, 30],
       [23, 55, 15]])

In [142]:
a_2d[0][0]

10

In [143]:
a_2d

array([[10, 20, 30],
       [23, 55, 15]])

In [144]:
a_2d[1][1]

55

In [145]:
a_2d

array([[10, 20, 30],
       [23, 55, 15]])

In [146]:
a_2d=np.array([[10,20,30],[23,55,15]],dtype=float)

In [147]:
a_2d

array([[10., 20., 30.],
       [23., 55., 15.]])

In [148]:
a_bigger=np.array([
[
[10,20,30,40],[8,8,2,1],[1,1,1,2]
],
[
[9,9,2,39],[1,2,3,3,],[0,0,3,2]
],
[
[12,33,22,1],[22,1,22,2],[0,2,3,1]
]    
],dtype=float)

In [149]:
a_bigger

array([[[10., 20., 30., 40.],
        [ 8.,  8.,  2.,  1.],
        [ 1.,  1.,  1.,  2.]],

       [[ 9.,  9.,  2., 39.],
        [ 1.,  2.,  3.,  3.],
        [ 0.,  0.,  3.,  2.]],

       [[12., 33., 22.,  1.],
        [22.,  1., 22.,  2.],
        [ 0.,  2.,  3.,  1.]]])

In [150]:
a_bigger.shape

(3, 3, 4)

In [151]:
a_bigger.ndim

3

In [152]:
a_bigger.size

36

In [153]:
a_bigger[2][2][3]

1.0

In [154]:
a_bigger[2][2]

array([0., 2., 3., 1.])

In [155]:
import numpy as np

In [156]:
a = np.array([20,30,60,80,76])

In [157]:
a.dtype

dtype('int32')

In [158]:
a.shape

(5,)

In [159]:
a.ndim

1

In [160]:
a[0]

20

In [161]:
a[2]

60

In [162]:
import numpy as np

In [163]:
a_2d= np.array([[50,60,10],[70,80,40]])

In [164]:
a_2d

array([[50, 60, 10],
       [70, 80, 40]])

In [165]:
a.dtype

dtype('int32')

In [166]:
a.shape

(5,)

In [167]:
a.size

5

In [168]:
a[0]

20

In [169]:
a[2]

60

In [170]:
np.full

<function numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)>

In [171]:
a_full = np.full((4,8,9), 5)

In [172]:
a_full

array([[[5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5,

In [173]:
a_full.ndim

3

In [174]:
a_zeros = np.zeros((3,3))

In [175]:
a_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [176]:
b_ones = np.ones((2,3,4))

In [177]:
b_ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [178]:
b_ones.ndim

3

In [179]:
e = np.empty((4,4,))

In [180]:
e

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23054293e-307],
       [2.22522597e-306, 1.33511969e-306, 1.37962320e-306,
        9.34604358e-307],
       [9.79101082e-307, 1.78020576e-306, 1.69119873e-306,
        2.22522868e-306],
       [1.24611809e-306, 8.06632139e-308, 1.60221208e-306,
        2.29178686e-312]])

In [181]:
b_random = np.random.random((2,2))

In [182]:
b_random

array([[0.79408915, 0.73866695],
       [0.5884911 , 0.86631984]])

In [183]:
b_random.ndim

2

In [184]:
b_random.size

4

In [185]:
a_arange = np.arange(10,50, 5)

In [186]:
a_arange

array([10, 15, 20, 25, 30, 35, 40, 45])

In [187]:
b_linspace = np.linspace(0,50,2)

In [188]:
b_linspace

array([ 0., 50.])

In [189]:
b_linspace.ndim

1

In [190]:
b_linspace.size

2

In [191]:
b_linspace1 = np.linspace(0,50,30)

In [192]:
b_linspace1

array([ 0.        ,  1.72413793,  3.44827586,  5.17241379,  6.89655172,
        8.62068966, 10.34482759, 12.06896552, 13.79310345, 15.51724138,
       17.24137931, 18.96551724, 20.68965517, 22.4137931 , 24.13793103,
       25.86206897, 27.5862069 , 29.31034483, 31.03448276, 32.75862069,
       34.48275862, 36.20689655, 37.93103448, 39.65517241, 41.37931034,
       43.10344828, 44.82758621, 46.55172414, 48.27586207, 50.        ])

In [193]:
b_linspace1.size

30

In [194]:
b_linspace2 = np.linspace(0,50,25, dtype=int)

In [195]:
b_linspace2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 50])

In [196]:
np.identity (8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [197]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [198]:
a

array([20, 30, 60, 80, 76])

In [199]:
np.exp(a)

array([4.85165195e+08, 1.06864746e+13, 1.14200739e+26, 5.54062238e+34,
       1.01480039e+33])

In [200]:
np.sin(a)

array([ 0.91294525, -0.98803162, -0.30481062, -0.99388865,  0.56610764])

In [201]:
np.cos(a)

array([ 0.40808206,  0.15425145, -0.95241298, -0.11038724,  0.82433133])

In [202]:
np.tan(a)

array([ 2.23716094, -6.4053312 ,  0.32004039,  9.00365495,  0.68674769])

In [203]:
np.log(a)

array([2.99573227, 3.40119738, 4.09434456, 4.38202663, 4.33073334])

In [204]:
np.sqrt(a)

array([4.47213595, 5.47722558, 7.74596669, 8.94427191, 8.71779789])

In [205]:
a.sum()

266

In [206]:
a.min()

20

In [207]:
a.mean()

53.2

In [208]:
np.median(a)

60.0

In [209]:
np.std(a)

24.18594633252956

In [210]:
np.median (b_linspace2)

25.0

In [211]:
np.sum (b_linspace2)

614

In [212]:
np.sqrt(b_linspace2)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595, 4.69041576, 5.        , 5.19615242, 5.38516481,
       5.56776436, 5.74456265, 5.91607978, 6.08276253, 6.244998  ,
       6.40312424, 6.55743852, 6.70820393, 6.8556546 , 7.07106781])

In [213]:
np.std(b_linspace2)

14.924020905908701

In [214]:
np.cos(b_linspace2)

array([ 1.        , -0.41614684, -0.65364362,  0.96017029, -0.14550003,
       -0.83907153,  0.84385396,  0.13673722, -0.95765948,  0.66031671,
        0.40808206, -0.99996083,  0.99120281, -0.29213881, -0.74805753,
        0.91474236, -0.01327675, -0.90369221,  0.76541405,  0.26664293,
       -0.98733928,  0.5551133 ,  0.52532199, -0.99233547,  0.96496603])

In [215]:
a_5d = np.array([[[25,55,36],[45,95,85],[15,75,88]]])

In [216]:
a_5d

array([[[25, 55, 36],
        [45, 95, 85],
        [15, 75, 88]]])

In [217]:
a_5d.dtype

dtype('int32')

In [218]:
a_5d.shape

(1, 3, 3)

In [219]:
a_5d.ndim

3

In [220]:
a[2]

60

In [221]:
a[0]

20

In [222]:
abb = np.empty((4,6))
abb

array([[1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
        3.46410162],
       [3.74165739, 4.        , 4.24264069, 4.47213595, 4.69041576,
        5.        ],
       [5.19615242, 5.38516481, 5.56776436, 5.74456265, 5.91607978,
        6.08276253],
       [6.244998  , 6.40312424, 6.55743852, 6.70820393, 6.8556546 ,
        7.07106781]])

In [223]:
b =np.random.random((6,7))
b

array([[0.54108576, 0.0322414 , 0.94949627, 0.12026252, 0.83587744,
        0.90083926, 0.11484099],
       [0.48366819, 0.67108412, 0.25992657, 0.27884066, 0.57582346,
        0.5896429 , 0.16375566],
       [0.06736222, 0.4199686 , 0.74104187, 0.36263507, 0.30595879,
        0.6129939 , 0.17611872],
       [0.73837831, 0.5141645 , 0.82178233, 0.71492443, 0.55671096,
        0.17534112, 0.39812509],
       [0.42618797, 0.76518203, 0.47787621, 0.18318582, 0.1457843 ,
        0.98869662, 0.29661124],
       [0.99747827, 0.27854393, 0.67836051, 0.01647666, 0.2217666 ,
        0.94652779, 0.0308862 ]])

In [224]:
c = np.full(((2,5)),12)
c

array([[12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12]])

In [225]:
s =np.full(((5,5)),0)
s

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [226]:
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [227]:
d = np.ones((8,8))
d

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [228]:
 njr = np.identity(6)

In [229]:
njr

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [230]:
#pandas

In [13]:
import pandas as pd

In [232]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [233]:
numbers = [20,20,30,40]

In [239]:
s= pd.Series(numbers)

In [241]:
print(s)

0    20
1    20
2    30
3    40
dtype: int64


In [15]:
marks =[70,80,90]
mark_Series =pd.Series(marks,index=["muneer","fayid","najma"])

In [17]:
print(mark_Series)

muneer    70
fayid     80
najma     90
dtype: int64
